### ISSUE TITLE
Time the app's display after the data is retrieved from the server

### ISSUE THREAD

**Issue by anandtharad** [anandtharad/QuizApp#4]
The app is not synced, that is, when the app is opened, instead of 1st question, the default text is displayed which might be due to the JSON object not getting enough time to retrieve the data and display it, and it interferes in the total number of questions to be answered.

**Comment by AnirudhPudari** [comment]
@anandtharad Hey, Can you assign this to me, I can take a look.

**Comment by anandtharad** [comment]
Here you go, @AnirudhPudari !

**Comment by AnirudhPudari** [comment]
@anandtharad Hey, You can review this PR https://github.com/anandtharad/QuizApp/pull/6 with the your exisiting bug resolved and also i have added an additional loading view for a better UI feel.
