### ISSUE TITLE
Making the app dynamic

### ISSUE THREAD

**Issue by anandtharad** [anandtharad/QuizApp#5]
As of now, the app considers default value of 10 questions that the user wants to answer.
Make a new activity and give the user the choice to select the number of questions to be answered.

**Comment by AnirudhPudari** [comment]
@anandtharad What will be the max and minimum number of questions that the user can select, is it starting in 10's, 20, 30....?

**Comment by anandtharad** [comment]
@AnirudhPudari ,the api used supports the values from 1 to 50 (inclusive)

**Comment by AnirudhPudari** [comment]
@anandtharad Assign this to me as well

**Comment by AnirudhPudari** [comment]
@anandtharad Hey, i think you shoud be good to go with these new changes. you can review and merge the changes.

**Comment by anandtharad** [comment]
Hey @AnirudhPudari , the app works fine for 10, 20, 30 questions, but crashes for 40 and 50. I have seen if it was there was some problem with API, but the API seems to work fine when searched in browser but somehow in the app, it is showing this error. It seems to me that the JSON object is not getting the count as 40 and 50, instead is getting as 0.

![image](https://user-images.githubusercontent.com/93462232/231503985-9bff4313-4027-41a9-9b50-a204d1553e34.png)

**Comment by anandtharad** [comment]
Thanks @AnirudhPudari for the help!
